### ISSUE TITLE
Make File Error 

### ISSUE THREAD

**Issue by Jonas-Verhellen** [nezix/QuickSES#1]
When trying to compile this interesting package with the supplied make file, i run into the following error:

```
nvcc -c -o CudaSurf.o CudaSurf.cu -Icpdb/ -use_fast_math -O3
nvcc -c -o SmoothMesh.o SmoothMesh.cpp -O3
nvcc -o QuickSES -O3 cpdb/cpdb.o cpdb/utils.o SmoothMesh.o CudaSurf.o
nvlink fatal   : Could not find fatbin in 'cpdb/cpdb.o'
nvlink fatal   : elfLink internal error
```
Could you please solve this, so that I can try out your package?

**Comment by nezix** [comment]
Can you try to compile cpdb.o with : ```g++ cpdb/cpdb.cpp -c -o cpdb/cpdb.o``` before running make.
You can also start from fresh with ```make clean && make```

What is your OS and your CUDA version ? What's your compiler ?

Compiling on Windows 10 / CUDA 11.1 works fine (I just tested it).

**Comment by Jonas-Verhellen** [comment]
Thank you for the swift answer. `make clean && make` solved the issue. I was running it on a Linux cluster / CUDA 11.0 for completeness. Thanks again.
