### ISSUE TITLE
Possible typo in RadiusDic

### ISSUE THREAD

**Issue by JarrettSJohnson** [nezix/QuickSES#4]
I wasn't sure if this is a typo here:

https://github.com/nezix/QuickSES/blob/master/CudaSurf.h#L70
```c++
radiusDic['S'] = 2.27f * factor;
```

For Sulfur, VDW radius is a bit less around 1.8A, whereas sodium is 2.27A.

**Comment by nezix** [comment]
Thanks, good catch
